# Generated by Django 4.0.5 on 2022-06-19 00:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salonname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('starttime', models.TimeField()),
                ('closetime', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('birthdate', models.DateField()),
                ('contact', models.CharField(max_length=14, verbose_name='Phone Number')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicename', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, upload_to='images')),
                ('salonid', models.ManyToManyField(to='salonapp.salon')),
            ],
        ),
        migrations.AddField(
            model_name='salon',
            name='stylistid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salonapp.user'),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('feedback', models.TextField(blank=True, max_length=720, null=True)),
                ('serviceid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salonapp.service')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salonapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('save', models.BooleanField()),
                ('salonid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salonapp.salon')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salonapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberofpeople', models.PositiveIntegerField()),
                ('amount', models.PositiveIntegerField()),
                ('status', models.BooleanField(default=False, verbose_name='approved')),
                ('date', models.TimeField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('serviceid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salonapp.service')),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='salonapp.user')),
            ],
        ),
    ]
